injectWaveforms([
'data/AC3_Boeing_Corporate_2k100629.ac3.png',
'data/AIFF_5 Kaskaskia River.aiff.png',
'data/AIFF_Lame3.98_The Pac-Keys - Greasy Pumpkin.aiff.png',
'data/CAF_Strange Bath.caf.png',
'data/FLAC_CarrollWalrusandCarpenter.flac.png',
'data/FLAC_The Pac-Keys - Greasy Pumpkin.flac.png',
'data/M4A_03 Strange Bath.m4a.png',
'data/M4A_applelossless_The Pac-Keys - Greasy Pumpkin.m4a.png',
'data/M4A_mp4_aac_128k_The Pac-Keys - Greasy Pumpkin.m4a.png',
'data/M4A_mp4_aac_The Pac-Keys - Greasy Pumpkin.m4a.png',
'data/MID_castles.mid.png',
'data/MP3_Lame3.92.Adriana Disman.mp3.png',
'data/MP3_Lame3.96_64Kb_CarrollWalrusandCarpenter.mp3.png',
'data/MP3_Lame3.97_64Kpbs_crime_and_punishment_01.mp3.png',
'data/MP3_Lame3.98_Teams - Anml Life.mp3.png',
'data/MP3_Lame3.98_The Pac-Keys - Greasy Pumpkin.mp3.png',
'data/MP3_Lame_ABR_The Pac-Keys - Greasy Pumpkin.mp3.png',
'data/MP3_Lame_CBR_The Pac-Keys - Greasy Pumpkin.mp3.png',
'data/MP3_Lame_VBR_The Pac-Keys - Greasy Pumpkin.mp3.png',
'data/MP3_VBR_JackJohnson2008-06-14.mp3.png',
'data/MP3_iTunes10.1.1_Blouse - Into Black.mp3.png',
'data/MP3_iTunes10.2.1_Telepathe - Hybrid Moments.mp3.png',
'data/MP3_iTunes10.3.1_Ghost Wave - On A Breeze.mp3.png',
'data/MP3_iTunes10.4_Oberhofer - Gotta Go.mp3.png',
'data/MP3_iTunes8.2.1_Slowdance - Sweetness.mp3.png',
'data/MP3_iTunes9.0.3_Blair - Hearts.m4a.png',
'data/MP3_iTunes9.0.3_Widows - Croc.mp3.png',
'data/MP3_iTunes9.2.1_Jonathan Wilson - Desert Raven.mp3.png',
'data/MP3_m2f_FlamencoGruv_Solo Guitar.mp3.png',
'data/MP3_unknown_Adventures of Huckleberry Finn_ch01.mp3.png',
'data/OGG_The Pac-Keys - Greasy Pumpkin.ogg.png',
'data/OGG_Tromboon-sample.ogg.png',
'data/OMF_biologii.omf.png.FAILED',
'data/PCM_bigendian_The Pac-Keys - Greasy Pumpkin.pcm.png.FAILED',
'data/PCM_littleendian_The Pac-Keys - Greasy Pumpkin.pcm.png.FAILED',
'data/W64_The Pac-Keys - Greasy Pumpkin.w64.png',
'data/WAV_The Pac-Keys - Greasy Pumpkin.wav.png',
'data/WAV_aac-ld_64.wav.png',
'data/WAV_airwick portugues diffuseair30_05.04.wav.png',
'data/WMA1_20_44.1sample.wma.png',
'data/WMA2_128_44.1-stereo-cbr.wma.png',
'data/WMA2_198_44.1_airwick portugues diffuseair.wma.png',
'data/WMA2_320_44.1-stereo-cbr.wma.png',
'data/WMA2_32_22_BachCPE_SonataAmin_1.wma.png',
'data/WMA2_32_44.1baroqueloop90z.wma.png',
'data/WV_The Pac-Keys - Greasy Pumpkin.wv.png',
'data/animals.mp3.png',
'data/midnight_city.mp3.png',
'data/mono.mp3.png',
'data/stereo.mp3.png',
'data/midnight_city.mp3.TINY.png',
'data/midnight_city.mp3.SMALL.png',
'data/midnight_city.mp3.LARGE.png',
'data/midnight_city.mp3.MAX.png',
]);
